import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const recursive = Recursive({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-recursive"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${recursive.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
